---
title: "Introduction"
subtitle: "Intro translated to Quarto"
format: html
editor: visual
---

## Research on plant responses to ultraviolet radiation {#sec:plants:UVB}

Plants are exposed to ultraviolet () radiation in their natural habitats. The amount and quality of radiation they are exposed to depends on the time of the year, the latitude, the elevation, position in the canopy, clouds and aerosols, and for aquatic plants the depth, solutes and particles contained in the water (see sections [1.4](#sec:solar:radiation){reference-type="ref" reference="sec:solar:radiation"} and [1.6](#sec:UV:aquatic){reference-type="ref" reference="sec:UV:aquatic"}). Ultraviolet radiation is consequently a carrier of information about the environment of plants. However, when exposed to enhanced doses of radiation or radiation of short wavelengths, plants can be damaged. When exposed to small doses of radiation plants respond by a mechanism involving the perception of the radiation through a photoreceptor called UVR8 [@Jenkins2009b; @Rizzini2011; @Wu2011; @Christie2012; @DiWu2012; @Heijde2012]. This protein behaves as a pigment at the top of a transduction chain that regulates gene expression. Several genes have been identified as regulated by radiation perceived through UVR8. Some are related to the metabolism of phenolic compounds and are involved in the accumulation of these metabolites.[^1] However, these are not the only genes regulated by UVR8. Genes related to hormone metabolism are also affected, and this could be one of the mechanisms for photomorphogenesis by radiation, for example an increase in leaf thickness or reduction in height of plants. Morphological effects of mediated by UVR8 have been described [@Wargent2009b].

The irradiance of in sunlight is larger than the irradiance of and plants also have photoreceptors that absorb both radiation and blue light. The best studied of these photoreceptors are cryptochromes and phototropins. Cryptochromes are involved in many photomorphogenic responses, including the accumulation of pigments. Phototropins are well known for their role in plant movements such as stomatal opening in blue light and the movement of chloroplasts [see @Christie2007; @Shimazaki2007; @Moeglich2010 for recent reviews].

The balance between the different wavebands, , and (photosynthetically active radiation, 400--700 nm), has a big influence on the effect of radiation on plants. Unrealistically low levels of radiation and enhance the effects of [e.g. @Caldwell1994c]. One reason for this is that radiation is required for photoreactivation, the repair of DNA damage in the light.

From the 1970's until the 1990's the main interest in research on the effects of on plants and other organisms was generated by the increase in ambient exposure caused by ozone depletion in the stratosphere [e.g. @Caldwell1971; @Caldwell1989; @Tevini1993; @Caldwell1994b]. This led to many studies on the effects of increased radiation, both outdoors, in greenhouses and in controlled environments. Frequently the results obtained in outdoor experiments differed from those obtained indoors. This lead to the realization that it is important to use realistic experimental conditions with respect to radiation and its ratio compared to other bands of the solar spectrum. Interactions of responses to radiation with other environmental factors like availability of mineral nutrients, water and temperature, were also uncovered. Effects on terrestrial and aquatic ecosystems of ozone depletion, and the concomitant increase in radiation, have been periodically reviewed in @UNEP2011 [and earlier reports]. These reports include chapters on terrestrial ecosystems [@Ballare2011] and aquatic ecosystems [@Hader2011].

From the 1990's onwards, the interest in the study of the effects of normal (i.e. without stratospheric ozone depletion), as opposed to enhanced radiation increased markedly [e.g. @Paul2001; @Aphalo2003; @Jansen2012]. This was in part due to the realization that even low exposures elicit plant responses, and that these are important for the acclimation of plants to their normal growth environment. Furthermore, as these effects were characterized, interest developed in their possible applications in agriculture and especially horticulture [e.g. @Paul2005].

A further subject of current interest is the enhanced release of greenhouse gases from green and dead biomass caused by action of radiation on pectins [e.g. @Messenger2009; @Bloom2010]. Another long-standing subject of research are the direct and indirect effects of solar radiation on litter decomposition [e.g. @Newsham1997a; @Newsham2001; @Austin2010].

To be able to obtain reliable results from experiments on the effects of radiation on plants, there are many different problems that need to be addressed. This requires background knowledge of both photobiology, radiation physics, and climatology.

## The principles of photochemistry {#sec:photobio:principles}

*Light* is electromagnetic radiation of wavelengths to which the human eye, as well as the photosynthetic apparatus, is sensitive ($\lambda \approx$ 400 to 700 nm). However, sometimes the word *light* is also used to refer to other nearby regions of the spectrum: ultraviolet (shorter wavelengths than visible light) and infra-red (longer wavelengths). Both particle and wave attributes of radiation are needed for a complete description of its behaviour. Light particles or quanta are called photons.

Sensing of visible and radiation by plants and other organisms starts as a photochemical event, and is ruled by the basic principles of photochemistry:

Grotthuss law

:   Only radiation that is actually absorbed can produce a chemical change.

Stark-Einstein law

:   Each absorbed quantum activates only one molecule.

As electrons in molecules can have only discrete energy levels, only photons that provide a quantity of energy adequate for an electron to 'jump' to another possible energetic state can be absorbed. The consequence of this is that substances have colours, i.e. they absorb photons with only certain energies. See @Nobel2009 and @Bjorn2007 for detailed descriptions of the interactions between light and matter.

